/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void win_draw1(PApplet appc, GWinData data) { //_CODE_:imageEdit:844393:
  appc.background(230);
} //_CODE_:imageEdit:844393:

public void imageData_changed(GTextArea source, GEvent event) { //_CODE_:imageData:934297:
  i_h.change_image_data(imageData.getText());
  
} //_CODE_:imageData:934297:

public void save_file_click1(GButton source, GEvent event) { //_CODE_:save_file:909706:
  i_h.save_image_data();
} //_CODE_:save_file:909706:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  imageEdit = GWindow.getWindow(this, "Window title", 0, 0, 400, 400, JAVA2D);
  imageEdit.noLoop();
  imageEdit.setActionOnClose(G4P.KEEP_OPEN);
  imageEdit.addDrawHandler(this, "win_draw1");
  imageData = new GTextArea(imageEdit, 0, 20, 400, 380, G4P.SCROLLBARS_BOTH);
  imageData.setOpaque(true);
  imageData.addEventHandler(this, "imageData_changed");
  label1 = new GLabel(imageEdit, 0, 0, 80, 20);
  label1.setText("Data:");
  label1.setOpaque(false);
  save_file = new GButton(imageEdit, 80, 0, 80, 20);
  save_file.setText("Save");
  save_file.addEventHandler(this, "save_file_click1");
  imageEdit.loop();
}

// Variable declarations 
// autogenerated do not edit
GWindow imageEdit;
GTextArea imageData; 
GLabel label1; 
GButton save_file; 
